on: push
name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Remove .vscode folder
      uses: JesseTG/rm@v1.0.2
      with:
        path: /.vscode
    - name: Remove .luacheckrc file
      uses: JesseTG/rm@v1.0.2
      with:
        path: /.luacheckrc
    - name: Publish Mod on mods.factorio.com
      uses: shanemadden/factorio-mod-portal-publish@stable
      env:
        FACTORIO_PASSWORD: ${{ secrets.FACTORIO_PASSWORD }}
        FACTORIO_USER: ${{ secrets.FACTORIO_USER }}
